pipeline:
  name: test-test
  identifier: testtest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        template:
          templateRef: account.remote_template
          versionLabel: V1
  properties:
    ci:
      codebase:
        connectorRef: account.CIPHERTron
        repoName: harness-ci-js
        build: <+input>
