name: Sample Pipeline_1676441602391
stages:
  - name: build
    spec:
      steps:
        - name: Script
          spec:
            run: echo hey
          type: script
        - name: npm_test
          spec:
            run: npm install
          type: script
        - name: npm_test
          spec:
            run: npm run test
          type: script
    type: ci
version: 1
